/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/jalanLowPoly.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function JalanLowPoly(props) {
  const { nodes, materials } = useGLTF('./models/jalanLowPoly.glb')
  return (
    <group {...props} dispose={null} castShadow>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 0.02, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[0, -2.65, 0]} scale={[1, 0.82, 1]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[0, -2.68, 0]} scale={[1, 0.82, 1]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[0, -2.68, 0]} scale={[1, 0.82, 1]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.004']} position={[83.57, 0.31, -25.85]} scale={[23.18, 23.18, 24.38]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.004']} position={[18.45, 14.45, -33.65]} scale={17.96} />
      <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.004']} morphTargetDictionary={nodes.Plane004.morphTargetDictionary} morphTargetInfluences={nodes.Plane004.morphTargetInfluences} position={[31.02, 0.06, -8.78]} scale={[21.86, 7.48, 7.48]} />
    </group>
  )
}

useGLTF.preload('./models/jalanLowPoly.glb')
