/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/Cloud.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cloud(props) {
  const { nodes, materials } = useGLTF("./models/Cloud.glb");
  return (
    <group {...props} dispose={null} castShadow>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials["Material.001"]}
        position={[0, 2.07, 0]}
        scale={0.94}
      />
    </group>
  );
}

useGLTF.preload("./models/Cloud.glb");
