/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/pohon.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from "@react-three/cannon";

export function TreeLP3(props) {
  const [ref] = useBox((index) => ({
    type: "Static",
    mass: 1,
    args: props.args,
    position: props.position,
    scale: props.scale,
    rotation: props.rotation,
    onCollide: (e) => {
      console.log(e);
    },
    ...props,
  }));
  const { nodes, materials } = useGLTF('./models/treeLP3.glb')
  return (
    <group {...props} dispose={null} ref={ref} castShadow>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0.07, 0.44, -0.02]} scale={0.41} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.002']} position={[0.07, 4.2, -0.02]} scale={[2.13, 2.16, 2.13]} />
    </group>
  )
}

useGLTF.preload('./models/treeLP3.glb')
