/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/treeLP2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/treeLP2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 0.69, 0]} scale={0.62} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} position={[0, 7.07, 0]} scale={[3.28, 4.01, 3.28]} />
    </group>
  )
}

useGLTF.preload('/treeLP2.glb')
