/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 assets\tree.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export function Tree(props) {
  const [ref] = useBox((index) => ({
    type: "Static",
    mass: 1,
    args: props.args,
    position: props.position,
    scale: props.scale,
    onCollide: (e) => {
      console.log(e);
    },
    ...props,
  }));
  const { nodes, materials } = useGLTF("/models/tree.glb");
  return (
    <group {...props} dispose={null} ref={ref} text={false}>
      <mesh
        castShadow
        geometry={nodes.tree.geometry}
        material={materials["Material.002"]}
      >
        <mesh
          geometry={nodes.leaves.geometry}
          material={materials["Material.001"]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/tree.glb");
